-- liquibase formatted sql

-- changeset anton:3
create table ads
(
    ad_id     bigint generated by default as identity,
    description  varchar(255),
    price        integer,
    title        varchar(255),
    ad_image_url varchar(255),
    user_id bigint,
    primary key (ad_id),
    foreign key (ad_image_url) references image(url),
    foreign key (user_id) references users(id)
);

-- create table comments
-- (
--     pk_comments_id  integer generated by default as identity,
--     created_at_date timestamp,
--     text            varchar(255),
--     ad_pk_ad_id     bigint,
--     user_user_id    bigint,
--     primary key (pk_comments_id)
-- );
--
-- create table image
-- (
--     url        varchar(255) not null,
--     data       varbinary(255),
--     file_path  varchar(255),
--     file_size  bigint       not null,
--     media_type varchar(255),
--     primary key (url)
-- );
--
-- create table users
-- (
--     id         bigint generated by default as identity,
--     email           varchar(255),
--     first_name      varchar(255),
--     last_name       varchar(255),
--     password        varchar(255),
--     phone           varchar(255),
--     role            varchar(255),
--     user_name_login varchar(255),
--     user_image_url  varchar(255),
--     primary key (user_id)
-- );