-- liquibase formatted sql

-- changeset anton:3
create table ads
(
    id     bigint generated by default as identity,
    description  varchar(255),
    price        integer,
    title        varchar(255) NOT NULL,
    ad_image_url bigint,
    users_id bigint NOT NULL,
    primary key (id),
    foreign key (ad_image_url) references image(url),
    foreign key (users_id) references users(id)
);