-- liquibase formatted sql

-- changeset anton:4
create table comments (
      pk_comments_id integer generated by default as identity,
      created_at_date timestamp,
      text varchar(255),
      ad_ad_id bigint,
      user_id bigint,
      primary key (pk_comments_id),
      foreign key (ad_ad_id) references ads(ad_id),
      foreign key (user_id) references users(id)

);

-- CREATE TABLE avatar
-- (
--     id         BIGSERIAL PRIMARY KEY,
--     data       BYTEA,
--     file_path  VARCHAR(255),
--     file_size  BIGINT,
--     media_type VARCHAR(255),
--     student_id_student bigint,
--     foreign key (student_id_student) references student(id_student)
-- );