-- liquibase formatted sql

-- changeset anton:4
create table comments (
      pk_comments_id integer generated by default as identity NOT NULL,
      created_at_date timestamp,
      text varchar(255) NOT NULL,
      ad_ad_id bigint NOT NULL,
      user_id bigint NOT NULL,
      primary key (pk_comments_id),
      foreign key (ad_ad_id) references ads(ad_id),
      foreign key (user_id) references users(id)

);