-- liquibase formatted sql

-- changeset anton:2
--condition tableExists:users
create table users
(
    id              bigint generated by default as identity,
    username varchar(50) NOT NULL UNIQUE,
    first_name      varchar(50),
    last_name       varchar(50),
    password        varchar(255) NOT NULL,
    phone           varchar(50),
    role            varchar(50),
    enabled         boolean,
    user_image_id  bigint,
    primary key (id),
    foreign key (user_image_id) references image(id)
);

